- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert
  
- name: "Copy getburpcert.sh to /tmp/getburpcert.sh"
  copy:
    src: files/getburpcert.sh
    dest: /tmp/getburpcert.sh
    mode: 0744
  when: burp_cert.stat.exists == False

- name: "Execute getburpcert.sh"
  shell:
    /tmp/getburpcert.sh
  when: burp_cert.stat.exists == False

- name: "Copy CA certificate to /usr/local/share/ca-certificates"
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False

- name: "Create directory for burp suite extras"
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

  #- name: Download jar files
  #ansible.builtin.get_url:
  #  url: "{{ item.value.url }}"
  #  dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
  #  checksum: "{{ item.value.checksum }}"
  #  mode: '0644'
  #become: true
  #become_method: sudo
  #loop: "{{ lookup('dict', burpsuite_extras_jars) }}"
  
- name: "Copy burp suite community config"
  template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigCommunity.json"
