- name: "Copy policies.json to /usr/share/firefox-esr/distribution/"
  template: 
    src: "templates/policies.json.j2"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
  become: true
  become_method: sudo

- name: "Delete default kali bookmarks"
  shell: "rm {{ ansible_env.HOME }}/.mozilla/firefox/*.default/places.sqlite"
