import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[colors.bright]
black = "0xffffff"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.normal]
black = "0x000000"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xe5c07b"

#[colors.primary]
#background = "#000000"
#foreground = "#FFFFFF"

#[colors.selection]
#background = "0xffffff"
#text = "CellForeground"

[cursor]
thickness = 0.1

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 10.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 15000

[window]
opacity = 1.0
padding = { x = 10, y = 10 }
