---
- name: "Install apt packages"
  apt:
    name:
      - tmux
      - alacritty
      - obsidian
      # neovim build prerequisites
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present
    update_cache: true
  become: true
  become_method: sudo
